### ISSUE TITLE
Can't run docker image

### ISSUE THREAD

**Issue by purpleraven** [zyddnys/manga-image-translator#120]
During simple run of builded image from docker hub I got error:

> docker-compose up

```
Recreating manga_image_translator_cpu ... done
Attaching to manga_image_translator_cpu
manga_image_translator_cpu | Traceback (most recent call last):
manga_image_translator_cpu |   File "/app/translate_demo.py", line 17, in <module>
manga_image_translator_cpu |     from text_mask import dispatch as dispatch_mask_refinement
manga_image_translator_cpu |   File "/app/text_mask/__init__.py", line 8, in <module>
manga_image_translator_cpu |     from .text_mask_utils import complete_mask_fill, filter_masks, complete_mask
manga_image_translator_cpu |   File "/app/text_mask/text_mask_utils.py", line 8, in <module>
manga_image_translator_cpu |     from sklearn.mixture import BayesianGaussianMixture
manga_image_translator_cpu | ModuleNotFoundError: No module named 'sklearn'
manga_image_translator_cpu exited with code 1
```

```
version: "3.3"
services:
  manga_image_translator:
    image: zyddnys/manga-image-translator:main
    container_name: manga_image_translator_cpu
    command: --verbose --log-web --mode web --use-inpainting --host=0.0.0.0 --port=5003
    volumes:
      - /home/translate/result:/app/result
    ports:
      - 5055:5003
    ipc: host
```
