### ISSUE TITLE
[Bug]: Errors in api mode

### ISSUE THREAD

**Issue by ryuzhaki** [zyddnys/manga-image-translator#594]
### Issue

When starting generation in web mode, everything works fine, but when switching to api mode, an error is thrown in response
`{"error": "Internal Server Error", "status": 500}`. There are no errors in the console.

```yml
version: "3.8"
services:
  mit:
    image: zyddnys/manga-image-translator:main
    ports:
      - 5003:5003
    command: -l ENG --manga2eng -v --mode web --host=0.0.0.0 --port=5003
```
Endpoints /run, /submit, /manual-translate
```bash
curl --location 'http://127.0.0.1:5003/run'  --form 'file=@"{full_path_to_file}"'
```
